### ISSUE TITLE
Fix hidden keyboard issues

### ISSUE THREAD

**Issue by revblaze** [raspu/Highlightr#11]
Amazing project you have going here! I am very intrigued. The only issue I seem to have encountered is the issue when attempting to scroll down to the bottom when the keyboard is up. You can even type behind the keyboard and the bottom of the code is missing too. Besides that, very stable project. Well done.

**Comment by raspu** [comment]
Thanks, I am glad you found Highlightr useful.
  
About the issue, is this a bug in the sample project? Because I don't think the library can interfere with the keyboard in any way... Would you please detail the issue a little more? Can you tell me what were you trying to do, what part of the library were you using, and maybe the steps to reproduce it?
