### ISSUE TITLE
Why don't you use singleton?

### ISSUE THREAD

**Issue by LeaderBoy** [raspu/Highlightr#15]
When the objects of CodeAttributedString and Highlightr  are increasing, it will block the interface

**Comment by raspu** [comment]
Syntax Highlighting is a slow process, even if we were not using JS to do it. Highlightr is doing this process in the calling thread because I am assuming the users will move this process to a background thread if they need to. CodeAttributedString, on the other hand, is managing this for you as it's dealing - indirectly - with the UI, so it's performing all the heavy logic on a background thread. 

As I see it using a singleton may help on iOS to make the app more efficient, but if you are using your threads correctly, you should never block the UI. Now, as it is right now highlightr it's: 1) Not thread-safe, and I really don't see the point of making it thread safe (Are you really going to highlight text from two different threads? What happens if you try to change the lang/theme while another thread is highlighting, shall we block the calling thread until is done? It's a slow process!) so making it a singleton it's not possible yet, and 2) it's keeping a lot of state; Theme and language are cached to make the highlighting process faster, and on my book a singleton make sense only for objects that are mostly state-less or keeping states that are intend to be shared. 

So, tbh if you are going to be creating too many Highlightr or CodeAttributedString objects think it's your responsibility to dispose your old instances or to reuse them when needed. As it is right now Highlightr is not designed to be used as a service.
