### ISSUE TITLE
How to build the framework without cocoapods

### ISSUE THREAD

**Issue by p0fi** [raspu/Highlightr#36]
I want to use just the framework but I cant build it. Is there a way to just build it without cocoapods?

**Comment by raspu** [comment]
Hi, currently there's no way to do this on the master branch, but there's a Carthage project on the develop branch I have been working on, I just updated it to use the latest code from master and seems to be building correctly, but I haven't tried to use it on a real project. Also, It's not configured to build an universal framework so you will need to build it either for device or for simulator. 

Let me know if this work for you!

**Comment by rudedogg** [comment]
Hey @raspu, haven't been involved with Highlightr for a bit. I'm toying around with Carthage, and was able to install Highlightr using the develop branch. I noticed there's an issue with the deployment target. It's not specified on the Project, and defaults to 10.12 (rather than 10.11). Should I just commit this to develop?

**Comment by raspu** [comment]
Thank you @rudedogg, let me know if you were able to use the dev. branch for this...

**Comment by rudedogg** [comment]
@raspu Yes, it works great! I had an edit to my previous comment saying this, but I must of closed the tab 😆.

**Comment by raspu** [comment]
You can use Carthage as alternative for CocoaPods starting from 2.0.1. I'll close this issue.
