### ISSUE TITLE
Support Swift PM

### ISSUE THREAD

**Issue by laosb** [raspu/Highlightr#76]
Supporting Swift PM would ease the development a lot.

**Comment by twodayslate** [comment]
@helje5 has a decent port that supports SPM
https://github.com/helje5/Highlightr

**Comment by helje5** [comment]
If there is a chance for acceptance, I could make it a proper PR. You may want to just wait for SPM resource support though.

The way my patch works is by bundling up the resources as Swift Strings using something I originally made for Server Side Swift ([SwiftWebResources](https://github.com/SwiftWebResources)). It's a little awkward because I bundle the resources as gzip'ed data (for web delivery).
But there is no specific reason why this couldn't be done inline in this project and live alongside the pod support.

**Comment by L1cardo** [comment]
Since Swift5.3 is now released, `.copy`can be implemented to support this feature.
https://developer.apple.com/documentation/swift_packages/bundling_resources_with_a_swift_package
