### ISSUE TITLE
[Question] Adjusting font size/font?

### ISSUE THREAD

**Issue by droidery** [raspu/Highlightr#8]
Is there a way to adjust the font-size and font that Highlightr uses in the attributes.

**Comment by rudedogg** [comment]
Hey @droidery

I do something similar using this:
```swift
if let codeFont = NSFont(name: "Source Code Pro", size: 14) {
    highlightr.theme.setCodeFont(codeFont)
}
```

`func setCodeFont(_ font: RPFont)` tries to get a normal/bold/unique version of the specified font and set it for the variables listed below.

If you'd rather specify a different font for the normal/bold/italic type, you could set these variables of the theme instance rather than calling `setCodeFont` (RPFont is just a typealias for `UIFont`/`NSFont` depending on the platform):
```swift
    open var codeFont : RPFont!
    open var boldCodeFont : RPFont!
    open var italicCodeFont : RPFont!
```

**Comment by Ivan-Cantarino** [comment]
Somehow I cannot put this to work when using `CodeAttributedString()` with `Markdown`

**Comment by wojciech-kulik** [comment]
I have found a solution. Pass to `CodeAttributedString` modified `Highlightr`:

```
final class MyHighlightr: Highlightr {
    var font: NSFont = NSFont.systemFont(ofSize: 16)

    override func highlight(_ code: String, as languageName: String? = nil, fastRender: Bool = true) -> NSAttributedString? {
        guard let result = super.highlight(code, as: languageName, fastRender: fastRender) else { return nil }

        let mutableResult = NSMutableAttributedString(attributedString: result)
        mutableResult.addAttribute(.font, value: font, range: .init(location: 0, length: result.length))

        return mutableResult
    }
}
```
